// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "../types/Types.res.js";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let configRef = {
  contents: undefined
};

let profileRef = {
  contents: undefined
};

let statsRef = {
  contents: undefined
};

async function sendMessage(msg) {
  return await chrome.runtime.sendMessage(msg);
}

async function loadState() {
  let configResult = await sendMessage({
    type: "GET_CONFIG",
    payload: undefined
  });
  configRef.contents = configResult;
  let profileResult = await sendMessage({
    type: "GET_CURRENT_PROFILE",
    payload: undefined
  });
  profileRef.contents = profileResult;
  let statsResult = await sendMessage({
    type: "GET_STATISTICS",
    payload: undefined
  });
  statsRef.contents = statsResult;
}

function updateProfileInfo() {
  let noProfile = document.getElementById("no-profile");
  let profileDetails = document.getElementById("profile-details");
  let match = profileRef.contents;
  if (match !== undefined) {
    if (!(noProfile == null) && !(profileDetails == null)) {
      noProfile.style.display = "none";
      profileDetails.style.display = "block";
      Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("profile-name")), el => {
        el.textContent = match.name;
      });
      Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("profile-age")), el => {
        el.textContent = match.demographics.age.toString();
      });
      Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("profile-occupation")), el => {
        el.textContent = match.demographics.occupationCategory;
      });
      Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("profile-interests")), el => {
        el.textContent = match.interests.map(Types.interestCategoryToString).join(", ");
      });
      return Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("profile-activity-level")), el => {
        el.textContent = Types.activityLevelToString(match.activityLevel);
      });
    } else {
      return;
    }
  } else if (!(noProfile == null) && !(profileDetails == null)) {
    noProfile.style.display = "block";
    profileDetails.style.display = "none";
    return;
  } else {
    return;
  }
}

function updateStatistics() {
  let stats = statsRef.contents;
  if (stats !== undefined) {
    Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("total-activities")), el => {
      el.textContent = stats.totalActivities.toString();
    });
    Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("today-activities")), el => {
      el.textContent = stats.activitiesToday.toString();
    });
    return Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("profile-age")), el => {
      el.textContent = stats.profileAgeDays.toString();
    });
  }
}

function updateUI() {
  let config = configRef.contents;
  if (config === undefined) {
    return;
  }
  let statusDot = document.getElementById("status-dot");
  let statusText = document.getElementById("status-text");
  let toggleBtn = document.getElementById("toggle-btn");
  if (!(statusDot == null) && !(statusText == null) && !(toggleBtn == null)) {
    if (config.enabled) {
      statusDot.classList.add("active");
      statusDot.classList.remove("inactive");
      statusText.textContent = "Enabled";
      toggleBtn.textContent = "Disable";
      toggleBtn.classList.add("active");
    } else {
      statusDot.classList.remove("active");
      statusDot.classList.add("inactive");
      statusText.textContent = "Disabled";
      toggleBtn.textContent = "Enable";
      toggleBtn.classList.remove("active");
    }
  }
  updateProfileInfo();
  updateStatistics();
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("noise-level")), slider => {
    let percentage = config.noiseLevel * 100.0 | 0;
    slider.value = percentage.toString();
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("noise-value")), el => {
    let percentage = config.noiseLevel * 100.0 | 0;
    el.textContent = percentage.toString() + `%`;
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("respect-schedule")), checkbox => {
    checkbox.checked = config.respectSchedule;
  });
}

async function handleToggle() {
  let config = configRef.contents;
  if (config === undefined) {
    return;
  }
  if (Stdlib_Option.isNone(profileRef.contents) && !config.enabled) {
    console.log("No profile exists. Generate one first.");
    return;
  }
  let newConfig_enabled = !config.enabled;
  let newConfig_currentProfile = config.currentProfile;
  let newConfig_noiseLevel = config.noiseLevel;
  let newConfig_respectSchedule = config.respectSchedule;
  let newConfig_privacyMode = config.privacyMode;
  let newConfig = {
    enabled: newConfig_enabled,
    currentProfile: newConfig_currentProfile,
    noiseLevel: newConfig_noiseLevel,
    respectSchedule: newConfig_respectSchedule,
    privacyMode: newConfig_privacyMode
  };
  await sendMessage({
    type: "UPDATE_CONFIG",
    payload: newConfig
  });
  await loadState();
  return updateUI();
}

async function handleGenerateProfile() {
  let generateBtn = document.getElementById("generate-profile-btn");
  if (generateBtn == null) {
    return;
  }
  generateBtn.textContent = "Generating...";
  generateBtn.disabled = true;
  let result = await sendMessage({
    type: "GENERATE_PROFILE",
    payload: undefined
  });
  profileRef.contents = result;
  await loadState();
  updateUI();
  generateBtn.textContent = "Generate New Profile";
  generateBtn.disabled = false;
}

async function handleNoiseChange(value) {
  let config = configRef.contents;
  if (config === undefined) {
    return;
  }
  let newLevel = Stdlib_Option.getOr(Stdlib_Float.fromString(value), 50.0) / 100.0;
  let newConfig_enabled = config.enabled;
  let newConfig_currentProfile = config.currentProfile;
  let newConfig_respectSchedule = config.respectSchedule;
  let newConfig_privacyMode = config.privacyMode;
  let newConfig = {
    enabled: newConfig_enabled,
    currentProfile: newConfig_currentProfile,
    noiseLevel: newLevel,
    respectSchedule: newConfig_respectSchedule,
    privacyMode: newConfig_privacyMode
  };
  await sendMessage({
    type: "UPDATE_CONFIG",
    payload: newConfig
  });
}

async function handleScheduleChange(checked) {
  let config = configRef.contents;
  if (config === undefined) {
    return;
  }
  let newConfig_enabled = config.enabled;
  let newConfig_currentProfile = config.currentProfile;
  let newConfig_noiseLevel = config.noiseLevel;
  let newConfig_privacyMode = config.privacyMode;
  let newConfig = {
    enabled: newConfig_enabled,
    currentProfile: newConfig_currentProfile,
    noiseLevel: newConfig_noiseLevel,
    respectSchedule: checked,
    privacyMode: newConfig_privacyMode
  };
  await sendMessage({
    type: "UPDATE_CONFIG",
    payload: newConfig
  });
}

async function handleClearHistory() {
  await sendMessage({
    type: "CLEAR_HISTORY",
    payload: undefined
  });
  await loadState();
  return updateUI();
}

function setupEventListeners() {
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("toggle-btn")), btn => {
    btn.addEventListener("click", param => {
      handleToggle();
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("generate-profile-btn")), btn => {
    btn.addEventListener("click", param => {
      handleGenerateProfile();
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("noise-level")), slider => {
    slider.addEventListener("input", e => {
      let value = e.target.value;
      Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("noise-value")), el => {
        el.textContent = value + `%`;
      });
    });
    slider.addEventListener("change", e => {
      handleNoiseChange(e.target.value);
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("respect-schedule")), checkbox => {
    checkbox.addEventListener("change", e => {
      handleScheduleChange(e.target.checked);
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("options-btn")), btn => {
    btn.addEventListener("click", param => {
      chrome.runtime.openOptionsPage();
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("clear-history-btn")), btn => {
    btn.addEventListener("click", param => {
      handleClearHistory();
    });
  });
}

async function initialize() {
  await loadState();
  setupEventListeners();
  return updateUI();
}

document.addEventListener("DOMContentLoaded", () => {
  initialize();
});

export {
  configRef,
  profileRef,
  statsRef,
  sendMessage,
  loadState,
  updateProfileInfo,
  updateStatistics,
  updateUI,
  handleToggle,
  handleGenerateProfile,
  handleNoiseChange,
  handleScheduleChange,
  handleClearHistory,
  setupEventListeners,
  initialize,
}
/*  Not a pure module */
