// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "../types/Types.res.js";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let configRef = {
  contents: undefined
};

let profileRef = {
  contents: undefined
};

let statsRef = {
  contents: undefined
};

async function sendMessage(msg) {
  return await chrome.runtime.sendMessage(msg);
}

async function loadState() {
  let configResult = await sendMessage({
    type: "GET_CONFIG",
    payload: undefined
  });
  configRef.contents = configResult;
  let profileResult = await sendMessage({
    type: "GET_CURRENT_PROFILE",
    payload: undefined
  });
  profileRef.contents = profileResult;
  let statsResult = await sendMessage({
    type: "GET_STATISTICS",
    payload: undefined
  });
  statsRef.contents = statsResult;
}

function updateProfileDisplay() {
  let noProfileMsg = document.getElementById("no-profile-message");
  let profileDetails = document.getElementById("profile-details");
  let exportBtn = document.getElementById("export-profile-btn");
  let match = profileRef.contents;
  if (match === undefined) {
    if (!(noProfileMsg == null) && !(profileDetails == null) && !(exportBtn == null)) {
      noProfileMsg.style.display = "block";
      profileDetails.style.display = "none";
      exportBtn.disabled = true;
      return;
    } else {
      return;
    }
  }
  if (noProfileMsg == null) {
    return;
  }
  if (profileDetails == null) {
    return;
  }
  if (exportBtn == null) {
    return;
  }
  noProfileMsg.style.display = "none";
  profileDetails.style.display = "block";
  exportBtn.disabled = false;
  let setField = (id, value) => Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById(id)), el => {
    el.textContent = value;
  });
  setField("profile-name", match.name);
  setField("profile-age", match.demographics.age.toString());
  setField("profile-gender", Types.genderToString(match.demographics.gender));
  setField("profile-location", match.demographics.locationType);
  setField("profile-occupation", match.demographics.occupationCategory);
  setField("profile-education", match.demographics.educationLevel);
  setField("profile-interests", match.interests.map(Types.interestCategoryToString).join(", "));
  setField("profile-style", Types.browsingStyleToString(match.browsingStyle));
  setField("profile-activity", Types.activityLevelToString(match.activityLevel));
}

function updateStatistics() {
  let stats = statsRef.contents;
  if (stats === undefined) {
    return;
  }
  let setField = (id, value) => Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById(id)), el => {
    el.textContent = value;
  });
  setField("total-activities", stats.totalActivities.toString());
  setField("today-activities", stats.activitiesToday.toString());
  setField("profile-age-days", stats.profileAgeDays.toString());
}

function updateUI() {
  let config = configRef.contents;
  if (config !== undefined) {
    Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("enabled")), el => {
      el.checked = config.enabled;
    });
    Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("privacy-mode")), el => {
      el.value = Types.privacyModeToString(config.privacyMode);
    });
    Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("noise-level")), slider => {
      let percentage = config.noiseLevel * 100.0 | 0;
      slider.value = percentage.toString();
    });
    Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("noise-value")), el => {
      let percentage = config.noiseLevel * 100.0 | 0;
      el.textContent = percentage.toString() + `%`;
    });
    Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("respect-schedule")), el => {
      el.checked = config.respectSchedule;
    });
    updateProfileDisplay();
    return updateStatistics();
  }
}

async function handleEnabledChange(enabled) {
  let match = configRef.contents;
  let match$1 = profileRef.contents;
  if (match === undefined) {
    return;
  }
  if (enabled && match$1 === undefined) {
    console.log("Please generate a profile first");
    return Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("enabled")), el => {
      el.checked = false;
    });
  }
  let newConfig_currentProfile = match.currentProfile;
  let newConfig_noiseLevel = match.noiseLevel;
  let newConfig_respectSchedule = match.respectSchedule;
  let newConfig_privacyMode = match.privacyMode;
  let newConfig = {
    enabled: enabled,
    currentProfile: newConfig_currentProfile,
    noiseLevel: newConfig_noiseLevel,
    respectSchedule: newConfig_respectSchedule,
    privacyMode: newConfig_privacyMode
  };
  await sendMessage({
    type: "UPDATE_CONFIG",
    payload: newConfig
  });
}

async function handleNoiseChange(value) {
  let config = configRef.contents;
  if (config === undefined) {
    return;
  }
  let newLevel = Stdlib_Option.getOr(Stdlib_Float.fromString(value), 50.0) / 100.0;
  let newConfig_enabled = config.enabled;
  let newConfig_currentProfile = config.currentProfile;
  let newConfig_respectSchedule = config.respectSchedule;
  let newConfig_privacyMode = config.privacyMode;
  let newConfig = {
    enabled: newConfig_enabled,
    currentProfile: newConfig_currentProfile,
    noiseLevel: newLevel,
    respectSchedule: newConfig_respectSchedule,
    privacyMode: newConfig_privacyMode
  };
  await sendMessage({
    type: "UPDATE_CONFIG",
    payload: newConfig
  });
}

async function handleScheduleChange(checked) {
  let config = configRef.contents;
  if (config === undefined) {
    return;
  }
  let newConfig_enabled = config.enabled;
  let newConfig_currentProfile = config.currentProfile;
  let newConfig_noiseLevel = config.noiseLevel;
  let newConfig_privacyMode = config.privacyMode;
  let newConfig = {
    enabled: newConfig_enabled,
    currentProfile: newConfig_currentProfile,
    noiseLevel: newConfig_noiseLevel,
    respectSchedule: checked,
    privacyMode: newConfig_privacyMode
  };
  await sendMessage({
    type: "UPDATE_CONFIG",
    payload: newConfig
  });
}

async function handleGenerateProfile() {
  let btn = document.getElementById("generate-profile-btn");
  if (btn == null) {
    return;
  }
  btn.textContent = "Generating...";
  btn.disabled = true;
  let result = await sendMessage({
    type: "GENERATE_PROFILE",
    payload: undefined
  });
  profileRef.contents = result;
  await loadState();
  updateUI();
  btn.textContent = "Generate New Profile";
  btn.disabled = false;
}

function handleExportProfile() {
  let profile = profileRef.contents;
  if (profile === undefined) {
    return;
  }
  let dataStr = Stdlib_Option.getOr(JSON.stringify(profile), "{}");
  console.log("Export profile:", dataStr);
}

function handleViewDashboard() {
  let url = chrome.runtime.getURL("dashboard.html");
  chrome.tabs.create({
    url: url,
    active: true
  });
}

async function handleClearHistory() {
  await sendMessage({
    type: "CLEAR_HISTORY",
    payload: undefined
  });
  await loadState();
  return updateUI();
}

function showModal() {
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("activity-modal")), modal => {
    modal.style.display = "flex";
  });
}

function closeModal() {
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("activity-modal")), modal => {
    modal.style.display = "none";
  });
}

function setupEventListeners() {
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("enabled")), el => {
    el.addEventListener("change", e => {
      handleEnabledChange(e.target.checked);
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("noise-level")), slider => {
    slider.addEventListener("input", e => {
      let value = e.target.value;
      Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("noise-value")), el => {
        el.textContent = value + `%`;
      });
    });
    slider.addEventListener("change", e => {
      handleNoiseChange(e.target.value);
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("respect-schedule")), el => {
    el.addEventListener("change", e => {
      handleScheduleChange(e.target.checked);
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("generate-profile-btn")), btn => {
    btn.addEventListener("click", param => {
      handleGenerateProfile();
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("export-profile-btn")), btn => {
    btn.addEventListener("click", param => handleExportProfile());
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("view-dashboard-btn")), btn => {
    btn.addEventListener("click", param => handleViewDashboard());
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("view-history-btn")), btn => {
    btn.addEventListener("click", param => showModal());
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("clear-history-btn")), btn => {
    btn.addEventListener("click", param => {
      handleClearHistory();
    });
  });
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.querySelector(".modal-close")), btn => {
    btn.addEventListener("click", param => closeModal());
  });
}

async function initialize() {
  await loadState();
  setupEventListeners();
  return updateUI();
}

document.addEventListener("DOMContentLoaded", () => {
  initialize();
});

export {
  configRef,
  profileRef,
  statsRef,
  sendMessage,
  loadState,
  updateProfileDisplay,
  updateStatistics,
  updateUI,
  handleEnabledChange,
  handleNoiseChange,
  handleScheduleChange,
  handleGenerateProfile,
  handleExportProfile,
  handleViewDashboard,
  handleClearHistory,
  showModal,
  closeModal,
  setupEventListeners,
  initialize,
}
/*  Not a pure module */
