// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "../types/Types.res.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let activitiesRef = {
  contents: []
};

let profileRef = {
  contents: undefined
};

let statsRef = {
  contents: undefined
};

async function loadData() {
  let keys = [
    Types.StorageKey.activityHistory,
    Types.StorageKey.profile,
    Types.StorageKey.statistics
  ];
  let result = await chrome.storage.local.get(keys);
  activitiesRef.contents = Stdlib_Option.getOr(Stdlib_Option.map(result[Types.StorageKey.activityHistory], prim => prim), []);
  profileRef.contents = Stdlib_Option.map(result[Types.StorageKey.profile], prim => prim);
  statsRef.contents = Stdlib_Option.map(result[Types.StorageKey.statistics], prim => prim);
}

function calculateStreak() {
  let activities = activitiesRef.contents;
  if (activities.length === 0) {
    return 0;
  }
  let today = new Date();
  ((today.setHours(0, 0, 0, 0)));
  let activityDates = activities.map(a => {
    let date = new Date(a.timestamp * 1000.0);
    ((date.setHours(0, 0, 0, 0)));
    return date.getTime();
  });
  let dateDict = {};
  activityDates.forEach(d => {
    dateDict[d.toString()] = true;
  });
  let hasDate = d => Stdlib_Option.isSome(dateDict[d.toString()]);
  let _currentDate = today.getTime();
  let _streak = 0;
  while (true) {
    let streak = _streak;
    let currentDate = _currentDate;
    if (!hasDate(currentDate)) {
      return streak;
    }
    _streak = streak + 1 | 0;
    _currentDate = currentDate - 86400000.0;
    continue;
  };
}

function showEmptyState() {
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.querySelector(".content")), content => {
    content.innerHTML = `
        <div class="empty-state">
          <div class="empty-state-icon">📊</div>
          <div class="empty-state-title">No Activity Data Yet</div>
          <div class="empty-state-text">
            Enable DoubleTrack and generate a profile to start seeing analytics
          </div>
        </div>
      `;
  });
}

function renderOverviewCards() {
  let activities = activitiesRef.contents;
  let stats = Stdlib_Option.getOr(statsRef.contents, {
    totalActivities: 0,
    activitiesToday: 0,
    profileAgeDays: 0,
    lastActivity: undefined,
    activityByType: {}
  });
  let setField = (id, value) => Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById(id)), el => {
    el.textContent = value;
  });
  setField("total-activities", stats.totalActivities.toString());
  let match = profileRef.contents;
  let avgPerDay;
  if (match !== undefined) {
    let days = Primitive_int.max(1, stats.profileAgeDays);
    avgPerDay = Primitive_int.div(stats.totalActivities, days);
  } else {
    avgPerDay = 0;
  }
  setField("daily-average", avgPerDay.toString());
  let totalSeconds = Stdlib_Array.reduce(activities, 0, (sum, a) => sum + a.durationSeconds | 0);
  let hours = totalSeconds / 3600 | 0;
  setField("total-duration", hours.toString() + `h`);
  let streak = calculateStreak();
  setField("streak-days", streak.toString());
}

function getDailyCounts(days) {
  let counts = Stdlib_Array.make(days, 0);
  let today = new Date();
  ((today.setHours(0, 0, 0, 0)));
  let todayTime = today.getTime();
  activitiesRef.contents.forEach(activity => {
    let activityDate = new Date(activity.timestamp * 1000.0);
    ((activityDate.setHours(0, 0, 0, 0)));
    let daysDiff = (todayTime - activityDate.getTime()) / 86400000.0 | 0;
    if (!(daysDiff >= 0 && daysDiff < days)) {
      return;
    }
    let idx = (days - 1 | 0) - daysDiff | 0;
    counts[idx] = Stdlib_Option.getOr(counts[idx], 0) + 1 | 0;
  });
  return counts;
}

function renderRecentActivities() {
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("recent-activities")), container => {
    let recent = activitiesRef.contents.slice(-20, activitiesRef.contents.length).toReversed();
    let icons = Object.fromEntries([
      [
        "Search",
        `🔍`
      ],
      [
        "PageVisit",
        `📄`
      ],
      [
        "VideoWatch",
        `🎥`
      ],
      [
        "Shopping",
        `🛒`
      ],
      [
        "SocialMedia",
        `💬`
      ],
      [
        "News",
        `📰`
      ],
      [
        "Research",
        `📚`
      ]
    ]);
    let html = recent.map(activity => {
      let typeStr = Types.activityTypeToString(activity.activityType);
      let icon = Stdlib_Option.getOr(icons[typeStr], `📄`);
      let date = new Date(activity.timestamp * 1000.0);
      let timeStr = date.toLocaleTimeString();
      return `
          <div class="activity-item">
            <div class="activity-icon">` + icon + `</div>
            <div class="activity-content">
              <div class="activity-title">` + activity.title + `</div>
              <div class="activity-url">` + activity.url + `</div>
            </div>
            <div class="activity-meta">` + timeStr + `</div>
          </div>
        `;
    }).join("");
    container.innerHTML = html;
  });
}

function renderInsights() {
  let profile = profileRef.contents;
  if (profile === undefined) {
    return;
  }
  let activities = activitiesRef.contents;
  let stats = Stdlib_Option.getOr(statsRef.contents, {
    totalActivities: 0,
    activitiesToday: 0,
    profileAgeDays: 0,
    lastActivity: undefined,
    activityByType: {}
  });
  let setField = (id, value) => Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById(id)), el => {
    el.textContent = value;
  });
  let age = profile.demographics.age.toString();
  let occupation = profile.demographics.occupationCategory.toLowerCase();
  let interestCount = profile.interests.length.toString();
  setField("insight-profile", `Your profile "` + profile.name + `" is a ` + age + `-year-old ` + occupation + ` with ` + interestCount + ` main interests.`);
  let activityCount = activities.length.toString();
  let days = stats.profileAgeDays.toString();
  let avgPerDay = Primitive_int.div(activities.length, Primitive_int.max(1, stats.profileAgeDays)).toString();
  setField("insight-activity", `Generated ` + activityCount + ` activities over ` + days + ` days, averaging ` + avgPerDay + ` per day.`);
  let style = Types.browsingStyleToString(profile.browsingStyle).toLowerCase();
  setField("insight-pattern", `Your ` + style + ` browsing style creates a natural, believable activity pattern.`);
  let level = Types.activityLevelToString(profile.activityLevel).toLowerCase();
  setField("insight-performance", `Activity level is ` + level + `, which provides good privacy coverage without excessive resource usage.`);
}

function renderDashboard() {
  if (activitiesRef.contents.length === 0) {
    return showEmptyState();
  } else {
    renderOverviewCards();
    renderRecentActivities();
    return renderInsights();
  }
}

function setupEventListeners() {
  Stdlib_Option.forEach(Primitive_option.fromNullable(document.getElementById("back-btn")), btn => {
    btn.addEventListener("click", param => {
      chrome.runtime.openOptionsPage();
      window.close();
    });
  });
}

async function initialize() {
  await loadData();
  setupEventListeners();
  return renderDashboard();
}

document.addEventListener("DOMContentLoaded", () => {
  initialize();
});

export {
  activitiesRef,
  profileRef,
  statsRef,
  loadData,
  calculateStreak,
  showEmptyState,
  renderOverviewCards,
  getDailyCounts,
  renderRecentActivities,
  renderInsights,
  renderDashboard,
  setupEventListeners,
  initialize,
}
/*  Not a pure module */
