// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Wasm from "../utils/Wasm.res.js";
import * as Storage from "../utils/Storage.res.js";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let isRunningRef = {
  contents: false
};

let fakeTabsRef = {
  contents: {}
};

function getNextMidnight() {
  let now = new Date();
  return ((function(now) {
      var d = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1);
      return d;
    }))(now).getTime();
}

function setupAlarms() {
  chrome.alarms.create("daily-reset", {
    when: getNextMidnight(),
    periodInMinutes: 24.0 * 60.0
  });
  chrome.alarms.create("update-profile-age", {
    periodInMinutes: 60.0 * 24.0
  });
}

function activeFakeTabCount() {
  return Object.keys(fakeTabsRef.contents).length;
}

async function closeFakeTab(tabId) {
  Stdlib_Dict.$$delete(fakeTabsRef.contents, tabId.toString());
  let val;
  try {
    val = await chrome.tabs.remove(tabId);
  } catch (_exn) {
    return;
  }
  console.log("DoubleTrack: Closed fake tab", tabId);
}

async function cleanupStaleFakeTabs() {
  let now = Date.now();
  let staleThreshold = 5.0 * 60.0 * 1000.0;
  let keys = Object.keys(fakeTabsRef.contents);
  await Stdlib_Array.reduce(keys, Promise.resolve(), async (accPromise, key) => {
    await accPromise;
    let info = fakeTabsRef.contents[key];
    if (info !== undefined && now - info.openedAt > staleThreshold) {
      return await closeFakeTab(info.tabId);
    }
  });
}

function getSimulationParams(activity) {
  let match = activity.activityType;
  let baseScroll;
  switch (match) {
    case "Search" :
      baseScroll = 0.3;
      break;
    case "PageVisit" :
      baseScroll = 0.7;
      break;
    case "VideoWatch" :
      baseScroll = 0.2;
      break;
    case "Shopping" :
      baseScroll = 0.5;
      break;
    case "SocialMedia" :
      baseScroll = 0.4;
      break;
    case "News" :
      baseScroll = 0.6;
      break;
    case "Research" :
      baseScroll = 0.8;
      break;
  }
  let scrollJitter = Math.random() * 0.3 - 0.15;
  let scrollDepth = Math.min(1.0, Math.max(0.1, baseScroll + scrollJitter));
  return {
    scrollDepth: scrollDepth,
    clickLinks: activity.activityType !== "Search" && Math.random() > 0.4,
    dwellSeconds: Primitive_int.max(5, activity.durationSeconds / 3 | 0),
    fillForms: false
  };
}

async function simulateActivity() {
  let config = await Storage.getConfig();
  let profile = await Storage.getProfile();
  let match = config.enabled;
  if (!match) {
    return;
  }
  if (profile === undefined) {
    return;
  }
  if (Object.keys(fakeTabsRef.contents).length >= 3) {
    console.log("DoubleTrack: At max fake tab capacity, skipping");
    return;
  }
  if (config.respectSchedule) {
    await Wasm.getActivitySchedule(profile);
  }
  let activities = await Wasm.generateActivities(profile, 0.25);
  if (activities.length === 0) {
    return;
  }
  let activity = activities[0];
  if (activity === undefined) {
    return;
  }
  await Storage.addActivity(activity);
  let tab = await chrome.tabs.create({
    url: activity.url,
    active: false
  });
  let tabId = tab.id;
  if (tabId !== undefined) {
    let info_openedAt = Date.now();
    let info = {
      tabId: tabId,
      activity: activity,
      openedAt: info_openedAt
    };
    fakeTabsRef.contents[tabId.toString()] = info;
    console.log("DoubleTrack: Opened fake tab", activity.url);
    let params = getSimulationParams(activity);
    setTimeout(() => {
      Stdlib_Promise.$$catch(chrome.tabs.sendMessage(tabId, {
        type: "SIMULATE_ACTIVITY",
        payload: params
      }).then(_response => {
        let closeDelay = (params.dwellSeconds + 5 | 0) * 1000 | 0;
        setTimeout(() => {
          closeFakeTab(tabId);
        }, closeDelay);
      }), _err => {
        setTimeout(() => {
          closeFakeTab(tabId);
        }, activity.durationSeconds * 1000 | 0);
        return Promise.resolve();
      });
    }, 3000);
    return;
  }
  console.error("DoubleTrack: Tab created but no ID returned");
}

async function handleAlarm(alarm) {
  let match = alarm.name;
  switch (match) {
    case "daily-reset" :
      return await Storage.resetDailyStatistics();
    case "simulate-activity" :
      if (isRunningRef.contents) {
        await cleanupStaleFakeTabs();
        return await simulateActivity();
      } else {
        return;
      }
    case "update-profile-age" :
      return await Storage.updateProfileAge();
    default:
      return;
  }
}

async function startSimulation() {
  if (isRunningRef.contents) {
    console.log("Simulation already running");
    return;
  }
  let config = await Storage.getConfig();
  let profile = await Storage.getProfile();
  if (profile !== undefined) {
    console.log("Starting activity simulation");
    isRunningRef.contents = true;
    let interval = 15.0 / config.noiseLevel;
    chrome.alarms.create("simulate-activity", {
      periodInMinutes: Math.max(5.0, interval)
    });
    return await simulateActivity();
  }
  console.error("No profile found, cannot start simulation");
}

async function stopSimulation() {
  console.log("Stopping activity simulation");
  isRunningRef.contents = false;
  chrome.alarms.clear("simulate-activity");
  let keys = Object.keys(fakeTabsRef.contents);
  await Stdlib_Array.reduce(keys, Promise.resolve(), async (accPromise, key) => {
    await accPromise;
    let info = fakeTabsRef.contents[key];
    if (info !== undefined) {
      return await closeFakeTab(info.tabId);
    }
  });
}

async function handleMessage(messageJson) {
  let match = messageJson.type;
  switch (match) {
    case "ACTIVITY_COMPLETE" :
      console.log("DoubleTrack: Content script reported activity complete");
      return {
        acknowledged: true
      };
    case "CLEAR_HISTORY" :
      await Storage.clearActivityHistory();
      return {
        success: true
      };
    case "GENERATE_PROFILE" :
      let seed = messageJson.payload;
      let profile = await Wasm.generateProfile(seed);
      await Storage.setProfile(profile);
      await Storage.clearActivityHistory();
      return profile;
    case "GET_CONFIG" :
      return await Storage.getConfig();
    case "GET_CURRENT_PROFILE" :
      return await Storage.getProfile();
    case "GET_STATISTICS" :
      return await Storage.getStatistics();
    case "SIMULATE_ACTIVITY" :
      await simulateActivity();
      return {
        success: true
      };
    case "UPDATE_CONFIG" :
      let config = messageJson.payload;
      await Storage.setConfig(config);
      if (config.enabled) {
        await startSimulation();
      } else {
        await stopSimulation();
      }
      return {
        success: true
      };
    default:
      return {
        error: `Unknown message type: ` + messageJson.type
      };
  }
}

function setupMessageListeners() {
  chrome.runtime["onMessage.addListener"]((message, _sender, sendResponse) => {
    Stdlib_Promise.$$catch(handleMessage(message).then(response => sendResponse(response)), error => {
      console.error("Error handling message:", error);
      sendResponse({
        error: "Internal error"
      });
      return Promise.resolve();
    });
    return true;
  });
}

async function initialize() {
  console.log("DoubleTrack Browser: Initializing background service");
  let exit = 0;
  let val;
  try {
    val = await Wasm.initialize();
    exit = 1;
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    console.error("Failed to initialize WASM core:", exn);
  }
  if (exit === 1) {
    console.log("WASM core initialized successfully");
  }
  setupMessageListeners();
  setupAlarms();
  chrome.alarms["onAlarm.addListener"](alarm => {
    handleAlarm(alarm);
  });
  chrome.tabs.onRemoved.addListener(tabId => Stdlib_Dict.$$delete(fakeTabsRef.contents, tabId.toString()));
  let config = await Storage.getConfig();
  if (config.enabled && Stdlib_Option.isSome(config.currentProfile)) {
    await startSimulation();
  }
  console.log("DoubleTrack Browser: Background service initialized");
}

initialize();

let maxConcurrentFakeTabs = 3;

export {
  isRunningRef,
  fakeTabsRef,
  maxConcurrentFakeTabs,
  getNextMidnight,
  setupAlarms,
  activeFakeTabCount,
  closeFakeTab,
  cleanupStaleFakeTabs,
  getSimulationParams,
  simulateActivity,
  handleAlarm,
  startSimulation,
  stopSimulation,
  handleMessage,
  setupMessageListeners,
  initialize,
}
/*  Not a pure module */
