// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE


let Local = {};

let Storage = {
  Local: Local
};

let LastError = {};

let Runtime = {
  LastError: LastError
};

let Alarms = {};

let OnRemoved = {};

let Tabs = {
  OnRemoved: OnRemoved
};

export {
  Storage,
  Runtime,
  Alarms,
  Tabs,
}
/* No side effect */
