// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE


let Document = {};

let Location = {};

let Window = {
  Location: Location
};

let Element = {};

let ClassList = {};

let Style = {};

let Event = {};

export {
  Document,
  Window,
  Element,
  ClassList,
  Style,
  Event,
}
/* No side effect */
