// Generated by ReScript, PLEASE EDIT WITH CARE


let StorageKey = {
  config: "doubletrack_config",
  profile: "doubletrack_profile",
  statistics: "doubletrack_statistics",
  activityHistory: "doubletrack_activity_history"
};

function genderToString(g) {
  switch (g) {
    case "Male" :
      return "Male";
    case "Female" :
      return "Female";
    case "NonBinary" :
      return "NonBinary";
    case "PreferNotToSay" :
      return "PreferNotToSay";
  }
}

function activityTypeToString(a) {
  switch (a) {
    case "Search" :
      return "Search";
    case "PageVisit" :
      return "PageVisit";
    case "VideoWatch" :
      return "VideoWatch";
    case "Shopping" :
      return "Shopping";
    case "SocialMedia" :
      return "SocialMedia";
    case "News" :
      return "News";
    case "Research" :
      return "Research";
  }
}

function privacyModeToString(p) {
  switch (p) {
    case "Full" :
      return "Full";
    case "Moderate" :
      return "Moderate";
    case "Minimal" :
      return "Minimal";
    case "Disabled" :
      return "Disabled";
  }
}

function browsingStyleToString(b) {
  switch (b) {
    case "Focused" :
      return "Focused";
    case "Explorer" :
      return "Explorer";
    case "Researcher" :
      return "Researcher";
    case "Casual" :
      return "Casual";
  }
}

function activityLevelToString(a) {
  switch (a) {
    case "Low" :
      return "Low";
    case "Medium" :
      return "Medium";
    case "High" :
      return "High";
    case "VeryHigh" :
      return "VeryHigh";
  }
}

function interestCategoryToString(i) {
  switch (i) {
    case "Technology" :
      return "Technology";
    case "Gaming" :
      return "Gaming";
    case "Sports" :
      return "Sports";
    case "Fitness" :
      return "Fitness";
    case "Cooking" :
      return "Cooking";
    case "Travel" :
      return "Travel";
    case "Fashion" :
      return "Fashion";
    case "Music" :
      return "Music";
    case "Movies" :
      return "Movies";
    case "Books" :
      return "Books";
    case "Art" :
      return "Art";
    case "Science" :
      return "Science";
    case "Politics" :
      return "Politics";
    case "News" :
      return "News";
    case "FinanceInterest" :
      return "Finance";
    case "HomeImprovement" :
      return "HomeImprovement";
    case "Gardening" :
      return "Gardening";
    case "Photography" :
      return "Photography";
    case "Programming" :
      return "Programming";
    case "DataScience" :
      return "DataScience";
  }
}

export {
  StorageKey,
  genderToString,
  activityTypeToString,
  privacyModeToString,
  browsingStyleToString,
  activityLevelToString,
  interestCategoryToString,
}
/* No side effect */
