// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let Window = {};

let Doc = {};

function dispatchMouseEvent(target, eventType) {
  ((function(target, eventType) {
      var rect = target.getBoundingClientRect();
      var x = rect.left + rect.width * Math.random();
      var y = rect.top + rect.height * Math.random();
      var evt = new MouseEvent(eventType, {
        bubbles: true, cancelable: true, view: window,
        clientX: x, clientY: y
      });
      target.dispatchEvent(evt);
    })(target, eventType));
}

function getScrollHeight() {
  return el.scrollHeight;
}

function simulateScroll(targetDepth, onComplete) {
  let maxScroll = getScrollHeight() - window.innerHeight;
  let targetY = {
    contents: 0.0
  };
  targetY.contents = maxScroll * targetDepth;
  let currentY = {
    contents: window.scrollY
  };
  let scrollStep = {
    contents: 0
  };
  let intervalId = {
    contents: 0
  };
  let step = () => {
    scrollStep.contents = scrollStep.contents + 1 | 0;
    let jitter = Math.random() * 80.0 + 20.0;
    currentY.contents = currentY.contents + jitter;
    if (currentY.contents >= targetY.contents || scrollStep.contents > 200) {
      clearInterval(intervalId.contents);
      return onComplete();
    } else {
      window.scrollTo({
        top: currentY.contents,
        behavior: "smooth"
      });
      return;
    }
  };
  let baseInterval = 100 + (Math.random() * 200.0 | 0) | 0;
  intervalId.contents = setInterval(step, baseInterval);
}

function simulateMouseMovement(onComplete) {
  let elements = document.querySelectorAll("p, h1, h2, h3, a, img, li, span");
  let numMoves = (Math.random() * 5.0 | 0) + 2 | 0;
  let moveIndex = {
    contents: 0
  };
  let doMove = () => {
    while (true) {
      if (moveIndex.contents >= numMoves || elements.length === 0) {
        return onComplete();
      }
      let idx = Math.random() * elements.length | 0;
      let el = elements[idx];
      if (el !== undefined) {
        let el$1 = Primitive_option.valFromOption(el);
        dispatchMouseEvent(el$1, "mouseover");
        dispatchMouseEvent(el$1, "mousemove");
        let delay = 300 + (Math.random() * 1200.0 | 0) | 0;
        setTimeout(() => {
          dispatchMouseEvent(el$1, "mouseout");
          moveIndex.contents = moveIndex.contents + 1 | 0;
          doMove();
        }, delay);
        return;
      }
      moveIndex.contents = moveIndex.contents + 1 | 0;
      continue;
    };
  };
  doMove();
}

function simulateClick(onComplete) {
  let links = document.querySelectorAll("a[href]");
  let internalLinks = (function(links) {
      return Array.from(links).filter(function(a) {
        try {
          var href = a.getAttribute('href');
          if (!href || href.startsWith('#') || href.startsWith('javascript:')) return false;
          var url = new URL(href, window.location.origin);
          return url.origin === window.location.origin;
        } catch(e) { return false; }
      });
    })(links);
  if (internalLinks.length === 0) {
    return onComplete();
  }
  let idx = Math.random() * internalLinks.length | 0;
  let link = internalLinks[idx];
  if (link === undefined) {
    return onComplete();
  }
  let link$1 = Primitive_option.valFromOption(link);
  dispatchMouseEvent(link$1, "mouseover");
  setTimeout(() => {
    dispatchMouseEvent(link$1, "click");
    onComplete();
  }, 500 + (Math.random() * 800.0 | 0) | 0);
}

function runSimulation(params, onComplete) {
  console.log("DoubleTrack: Starting page behavior simulation");
  simulateScroll(params.scrollDepth, () => simulateMouseMovement(() => {
    if (params.clickLinks && Math.random() > 0.5) {
      return simulateClick(() => {
        setTimeout(onComplete, params.dwellSeconds * 1000 | 0);
      });
    } else {
      setTimeout(onComplete, params.dwellSeconds * 1000 | 0);
      return;
    }
  }));
}

chrome.runtime["onMessage.addListener"]((messageJson, _sender, sendResponse) => {
  let match = messageJson.type;
  switch (match) {
    case "GET_PAGE_INFO" :
      sendResponse({
        url: window.location.href,
        title: document.title,
        timestamp: Date.now()
      });
      break;
    case "PING" :
      sendResponse({
        status: "alive"
      });
      break;
    case "SIMULATE_ACTIVITY" :
      let p = messageJson.payload;
      let params = p !== undefined ? p : ({
          scrollDepth: 0.6,
          clickLinks: true,
          dwellSeconds: 15,
          fillForms: false
        });
      runSimulation(params, () => {
        console.log("DoubleTrack: Simulation complete, signaling background");
        chrome.runtime.sendMessage({
          type: "ACTIVITY_COMPLETE",
          payload: null
        });
      });
      sendResponse({
        status: "simulation_started"
      });
      break;
    default:
      sendResponse({
        error: "Unknown message type"
      });
  }
  return true;
});

export {
  Window,
  Doc,
  dispatchMouseEvent,
  getScrollHeight,
  simulateScroll,
  simulateMouseMovement,
  simulateClick,
  runSimulation,
}
/*  Not a pure module */
