// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "../types/Types.res.js";

let defaultConfig = {
  enabled: false,
  currentProfile: undefined,
  noiseLevel: 0.5,
  respectSchedule: true,
  privacyMode: "Moderate"
};

function defaultStatistics() {
  return {
    totalActivities: 0,
    activitiesToday: 0,
    profileAgeDays: 0,
    lastActivity: undefined,
    activityByType: {}
  };
}

async function getConfig() {
  let result = await chrome.storage.local.get(Types.StorageKey.config);
  let json = result[Types.StorageKey.config];
  if (json !== undefined) {
    return json;
  } else {
    return defaultConfig;
  }
}

async function setConfig(config) {
  let dict = {};
  dict[Types.StorageKey.config] = config;
  return await chrome.storage.local.set(dict);
}

async function getProfile() {
  let result = await chrome.storage.local.get(Types.StorageKey.profile);
  let json = result[Types.StorageKey.profile];
  if (json !== undefined) {
    return json;
  }
}

async function setProfile(profile) {
  let dict = {};
  dict[Types.StorageKey.profile] = profile;
  return await chrome.storage.local.set(dict);
}

async function getStatistics() {
  let result = await chrome.storage.local.get(Types.StorageKey.statistics);
  let json = result[Types.StorageKey.statistics];
  if (json !== undefined) {
    return json;
  } else {
    return {
      totalActivities: 0,
      activitiesToday: 0,
      profileAgeDays: 0,
      lastActivity: undefined,
      activityByType: {}
    };
  }
}

async function setStatistics(stats) {
  let dict = {};
  dict[Types.StorageKey.statistics] = stats;
  return await chrome.storage.local.set(dict);
}

async function getActivityHistory() {
  let result = await chrome.storage.local.get(Types.StorageKey.activityHistory);
  let json = result[Types.StorageKey.activityHistory];
  if (json !== undefined) {
    return json;
  } else {
    return [];
  }
}

async function addActivity(activity) {
  let history = await getActivityHistory();
  let newHistory = history.concat([activity]);
  let trimmedHistory = newHistory.length > 1000 ? newHistory.slice(newHistory.length - 1000 | 0, newHistory.length) : newHistory;
  let dict = {};
  dict[Types.StorageKey.activityHistory] = trimmedHistory;
  await chrome.storage.local.set(dict);
  let stats = await getStatistics();
  stats.totalActivities = stats.totalActivities + 1 | 0;
  stats.lastActivity = activity.timestamp;
  let today = new Date();
  ((today.setHours(0, 0, 0, 0)));
  let activityDate = new Date(activity.timestamp * 1000.0);
  if (activityDate.getTime() >= today.getTime()) {
    stats.activitiesToday = stats.activitiesToday + 1 | 0;
  }
  let typeStr = Types.activityTypeToString(activity.activityType);
  let c = stats.activityByType[typeStr];
  let currentCount = c !== undefined ? c : 0;
  stats.activityByType[typeStr] = currentCount + 1 | 0;
  return await setStatistics(stats);
}

async function clearActivityHistory() {
  let dict = {};
  dict[Types.StorageKey.activityHistory] = [];
  await chrome.storage.local.set(dict);
  return await setStatistics({
    totalActivities: 0,
    activitiesToday: 0,
    profileAgeDays: 0,
    lastActivity: undefined,
    activityByType: {}
  });
}

async function resetDailyStatistics() {
  let stats = await getStatistics();
  stats.activitiesToday = 0;
  return await setStatistics(stats);
}

async function updateProfileAge() {
  let profile = await getProfile();
  if (profile === undefined) {
    return;
  }
  let stats = await getStatistics();
  let now = Date.now() / 1000.0;
  let ageSeconds = now - profile.createdAt;
  stats.profileAgeDays = ageSeconds / 86400.0 | 0;
  return await setStatistics(stats);
}

export {
  defaultConfig,
  defaultStatistics,
  getConfig,
  setConfig,
  getProfile,
  setProfile,
  getStatistics,
  setStatistics,
  getActivityHistory,
  addActivity,
  clearActivityHistory,
  resetDailyStatistics,
  updateProfileAge,
}
/* No side effect */
