// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let wasmModuleRef = {
  contents: undefined
};

let initializedRef = {
  contents: false
};

let importWasmModule = (function() {
    // wasm-pack produces a JS glue file alongside the .wasm binary
    // In the built extension, it lives at wasm/doubletrack_core.js
    return import(chrome.runtime.getURL('wasm/doubletrack_core.js'))
      .then(function(mod) {
        // wasm-pack web target exports a default init function
        if (mod.default && typeof mod.default === 'function') {
          return mod.default().then(function() { return mod; });
        }
        return mod;
      });
  });

async function initialize() {
  if (initializedRef.contents) {
    return;
  }
  let wasmModule;
  try {
    wasmModule = await importWasmModule();
  } catch (_exn) {
    console.warn("DoubleTrack: WASM load failed, falling back to mock engine");
    initializedRef.contents = true;
    return;
  }
  wasmModuleRef.contents = Primitive_option.some(wasmModule);
  initializedRef.contents = true;
  console.log("DoubleTrack: WASM core loaded successfully");
}

async function ensureInitialized() {
  if (!initializedRef.contents) {
    return await initialize();
  }
}

function callWasm(fnName, args) {
  let m = wasmModuleRef.contents;
  if (m === undefined) {
    return;
  }
  let fn = (function(m, name) { return m[name]; })(Primitive_option.valFromOption(m), fnName);
  if (fn !== undefined) {
    return Primitive_option.some((function(f, args) { return f.apply(null, args); })(Primitive_option.valFromOption(fn), args));
  }
}

function mockGenerateProfile(seed) {
  let timestamp = Date.now();
  let randStr = Math.random().toString();
  let randPart = randStr.slice(2, randStr.length);
  let id = `profile_` + timestamp.toString() + `_` + randPart;
  let names = [
    "Alex Smith",
    "Jordan Johnson",
    "Taylor Williams",
    "Casey Brown",
    "Morgan Davis"
  ];
  let nameIndex = seed !== undefined ? seed % 5 : Math.floor(Math.random() * 5.0) | 0;
  let name = Stdlib_Option.getOr(names[nameIndex], "Alex Smith");
  let allInterests = [
    "Technology",
    "Gaming",
    "Sports",
    "Fitness",
    "Cooking",
    "Travel",
    "Fashion",
    "Music",
    "Movies",
    "Books",
    "Art",
    "Science",
    "News",
    "FinanceInterest",
    "HomeImprovement",
    "Photography",
    "Programming",
    "DataScience"
  ];
  let numInterests = 3 + (Math.floor(Math.random() * 4.0) | 0) | 0;
  let shuffled = allInterests.slice();
  for (let i = 0; i < numInterests; ++i) {
    let j = i + (Math.floor(Math.random() * (shuffled.length - i | 0)) | 0) | 0;
    let tmp = Stdlib_Option.getOrThrow(shuffled[i], "shuffle source index");
    shuffled[i] = Stdlib_Option.getOrThrow(shuffled[j], "shuffle swap index");
    shuffled[j] = tmp;
  }
  let interests = shuffled.slice(0, numInterests);
  let genders = [
    "Male",
    "Female",
    "NonBinary",
    "PreferNotToSay"
  ];
  let gender = Stdlib_Option.getOr(genders[Math.floor(Math.random() * 4.0) | 0], "Male");
  let locations = [
    "Urban",
    "Suburban",
    "Rural"
  ];
  let locationType = Stdlib_Option.getOr(locations[Math.floor(Math.random() * 3.0) | 0], "Urban");
  let styles = [
    "Focused",
    "Explorer",
    "Researcher",
    "Casual"
  ];
  let browsingStyle = Stdlib_Option.getOr(styles[Math.floor(Math.random() * 4.0) | 0], "Explorer");
  let levels = [
    "Low",
    "Medium",
    "High",
    "VeryHigh"
  ];
  let activityLevel = Stdlib_Option.getOr(levels[Math.floor(Math.random() * 4.0) | 0], "Medium");
  return {
    id: id,
    name: name,
    demographics: {
      age: 22 + (Math.floor(Math.random() * 45.0) | 0) | 0,
      gender: gender,
      locationType: locationType,
      occupationCategory: "Technology",
      educationLevel: "Bachelor"
    },
    interests: interests,
    browsingStyle: browsingStyle,
    activityLevel: activityLevel,
    createdAt: Date.now() / 1000.0
  };
}

let mockSearchQueries = [
  "best coffee shops nearby",
  "how to fix a leaky faucet",
  "latest smartphone reviews 2026",
  "healthy dinner recipes under 30 minutes",
  "vintage car restoration tips",
  "Slovenian poetry translations",
  "home espresso machine comparison",
  "weekend hiking trails",
  "beginner piano lessons online",
  "climate change research papers",
  "best board games for adults",
  "how to start a vegetable garden",
  "mechanical keyboard guide",
  "travel insurance comparison",
  "history of Japanese ceramics"
];

let mockDomains = [
  "reddit.com",
  "stackoverflow.com",
  "medium.com",
  "theguardian.com",
  "arstechnica.com",
  "bbc.com",
  "allrecipes.com",
  "instructables.com",
  "wikipedia.org",
  "youtube.com",
  "nytimes.com",
  "bonappetit.com",
  "nature.com",
  "wired.com"
];

function mockGenerateActivities(profile, durationHours) {
  let baseTime = Date.now() / 1000.0;
  let activitiesCount = Primitive_int.max(1, durationHours * 4.0 | 0);
  let activityTypes = [
    "Search",
    "PageVisit",
    "VideoWatch",
    "Shopping",
    "SocialMedia",
    "News",
    "Research"
  ];
  return Stdlib_Array.fromInitializer(activitiesCount, i => {
    let timestamp = baseTime + i * 900.0 + Math.random() * 300.0;
    let at = Stdlib_Option.getOr(activityTypes[Math.floor(Math.random() * activityTypes.length) | 0], "PageVisit");
    let queryIdx = Math.floor(Math.random() * mockSearchQueries.length) | 0;
    let domainIdx = Math.floor(Math.random() * mockDomains.length) | 0;
    let query = Stdlib_Option.getOr(mockSearchQueries[queryIdx], "latest news");
    let domain = Stdlib_Option.getOr(mockDomains[domainIdx], "example.com");
    let match;
    switch (at) {
      case "Search" :
        let encoded = query.replace(/\\s+/g, "+");
        match = [
          `https://www.google.com/search?q=` + encoded,
          query + ` - Google Search`
        ];
        break;
      case "VideoWatch" :
        let vidStr = Math.random().toString();
        let vidId = vidStr.slice(2, vidStr.length).slice(0, 11);
        match = [
          `https://www.youtube.com/watch?v=` + vidId,
          `Video: ` + query
        ];
        break;
      default:
        match = [
          `https://` + domain + `/` + query.replace(/\\s+/g, "-").toLowerCase(),
          query + ` | ` + domain
        ];
    }
    return {
      activityType: at,
      url: match[0],
      title: match[1],
      durationSeconds: 30 + (Math.floor(Math.random() * 240.0) | 0) | 0,
      timestamp: timestamp,
      interestCategory: profile.interests[Math.floor(Math.random() * profile.interests.length) | 0]
    };
  });
}

function mockGetSchedule(_profile) {
  return {
    timePatterns: [],
    timezoneOffset: 0
  };
}

async function generateProfile(seed) {
  await ensureInitialized();
  let seedArg = seed !== undefined ? seed : null;
  let result = callWasm("generate_profile", [seedArg]);
  if (result !== undefined) {
    return Primitive_option.valFromOption(result);
  } else {
    return mockGenerateProfile(seed);
  }
}

async function generateActivities(profile, durationHours) {
  await ensureInitialized();
  let result = callWasm("generate_activities", [
    profile,
    durationHours
  ]);
  if (result !== undefined) {
    return Primitive_option.valFromOption(result);
  } else {
    return mockGenerateActivities(profile, durationHours);
  }
}

async function validateProfile(profile) {
  await ensureInitialized();
  let result = callWasm("validate_profile", [profile]);
  if (result !== undefined) {
    return Primitive_option.valFromOption(result);
  } else if (profile.name !== "" && profile.interests.length !== 0) {
    return profile.demographics.age >= 18;
  } else {
    return false;
  }
}

async function getActivitySchedule(profile) {
  await ensureInitialized();
  let result = callWasm("get_activity_schedule", [profile]);
  if (result !== undefined) {
    return Primitive_option.valFromOption(result);
  } else {
    return {
      timePatterns: [],
      timezoneOffset: 0
    };
  }
}

export {
  wasmModuleRef,
  initializedRef,
  importWasmModule,
  initialize,
  ensureInitialized,
  callWasm,
  mockGenerateProfile,
  mockSearchQueries,
  mockDomains,
  mockGenerateActivities,
  mockGetSchedule,
  generateProfile,
  generateActivities,
  validateProfile,
  getActivitySchedule,
}
/* No side effect */
